using System;
using System.Collections.Generic;
using System.Numerics;
using ZodiacBuddy.Stages.Animus.Data;
using ZodiacBuddy.Systems.Fates;

namespace ZodiacBuddy.Stages.Animus;

internal sealed class FateAutomationContext
{
    internal FateAutomationState AutomationState = FateAutomationState.Idle;
    internal string AutomationStatus = "Idle";
    internal FateExecutionRequest Request;
    internal FateExecutionResult RuntimeResult = FateExecutionResult.None;
    internal FateExecutionResult FinalResult = FateExecutionResult.None;
    internal FateObjectiveDefinition BookTarget;
    internal bool HasBookTarget;
    internal uint BookId;
    internal bool ProbeOnlyWhenAbsent;
    internal long AutomationRunId;
    internal DateTime AutomationStateDeadline;
    internal DateTime ProbeReadyAt;
    internal DateTime NextTeleportRetryAt;
    internal bool TeleportCastObserved;
    internal DateTime TeleportCastEndedAt;
    internal uint TeleportAetheryteId;
    internal int TeleportAttempts;
    internal uint TeleportStartTerritoryId;
    internal Vector3? TeleportStartPosition;
    internal Vector3? TeleportDestinationPosition;
    internal bool TeleportTransitionObserved;
    internal bool TeleportScreenNotReadyObserved;
    internal bool TeleportTerritoryChangeObserved;
    internal bool TeleportDestinationRecoveryLogged;
    internal DateTime CreditDeadline;
    internal bool NavmeshWaitRequested;
    internal bool NavigationActive;
    internal Vector3? NavigationDestination;
    internal FateNavigationIntent NavigationIntent;
    internal bool NavigationFly;
    internal bool UGhamaroMineGroundTravelActive;
    internal DateTime LineOfSightRecoveryRetryAt;
    internal bool DismountQueued;
    internal DateTime DismountDeadline;
    internal Vector3? LandingRecoveryAnchor;
    internal int LandingRecoveryAttempts;
    internal ushort WorkingFateId;
    internal bool WorkingFateIsPrerequisite;
    internal bool WorkingFateObservedPreparing;
    internal bool WorkingFateObservedRunning;
    internal bool WorkingFateCompletionObserved;
    internal DateTime WorkingFateMissingSince;
    internal bool TargetObservedRunning;
    internal bool TargetParticipated;
    internal bool PrerequisiteDone;
    internal FatePostCombatOutcome PostCombatOutcome;
    internal ulong CombatTargetId;
    internal DateTime NoCombatTargetSince;
    internal ulong IncidentalAggroTargetId;
    internal ulong InteractionTargetId;
    internal ulong StarterObjectId;
    internal ulong EscortAnchorId;
    internal DateTime EscortFollowRestartAt;
    internal ulong DefendAnchorId;
    internal DateTime EventObjectSafeAt;
    internal bool CollectTurnInActive;
    internal DateTime CollectTurnInSafeAt;
    internal int CollectTurnInStartItemCount;
    internal int CollectRequestFillSlot;
    internal ulong CollectRequestSubmitAfterFrame;
    internal Vector3? StagingDestination;
    internal int EntryArrivalMisses;
    internal DateTime EntryArrivalGraceUntil;
    internal ulong EntryAnchorId;
    internal Vector3? EntryAnchorDestination;
    internal DateTime FillerStartDeadline;
    internal bool PreemptionPending;
    internal string PreemptionReason = string.Empty;
    internal ushort PreemptionFateId;
    internal Vector3 PreemptionFateCenter;
    internal float PreemptionFateRadius;
    internal DateTime PreemptionUnsyncNextAttemptAt;
    internal int PreemptionUnsyncAttempts;
    internal bool FinishFillerBeforeYield;
    internal string DeferredTerminalStatus = string.Empty;
    internal HashSet<ulong> KnownCombatEnemyIds { get; } = [];
    internal Vector3? ResidualAggroOrigin;
    internal ulong ResidualLoggedTargetId;
    internal ulong ResidualDiagnosticTargetId;
    internal ushort ResidualDiagnosticFateId;
    internal DateTime ResidualDiagnosticNextAt;
}
